Repository wecode-bootcamp-korea/11-DevX-frontend, pull requests merged in 2020-08, with the labels that each got.

#1 [DevX] Modify: common.scss 식별자 수정 및 mixin 추가
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: Status: 리뷰 요청

#3 [황연욱] 초기 레이아웃 구현(Scroll이벤트, Slider기능 들어간 컴포넌트제외 나머지 컴포넌트들만 우선적으로 구현)
  public/images/falcon9/F9_1.jpg
  public/images/falcon9/F9_10.jpg
  public/images/falcon9/F9_2.jpg
  public/images/falcon9/F9_3.jpg
  public/images/falcon9/F9_4.jpg
  public/images/falcon9/F9_5.jpg
  public/images/falcon9/F9_6.jpg
  public/images/falcon9/F9_7.jpg
  public/images/falcon9/F9_8.jpg
  public/images/falcon9/F9_9.jpg
  public/images/falcon9/f9Feature.webp
  public/images/falcon9/f9VideoThumbnail.jpg
  public/images/falcon9/merlinSeaLevel.webp
  public/images/falcon9/merlinVacuum.webp
  src/Pages/falcon9/Engines/Engines.js
  src/Pages/falcon9/Engines/Engines.scss
  src/Pages/falcon9/Falcon9.js
  src/Pages/falcon9/Falcon9.scss
  src/Pages/falcon9/Video/Video.js
  src/Pages/falcon9/Video/Video.scss
  src/Pages/falcon9/feature/Featuer.js
  src/Pages/falcon9/feature/Feature.scss
  src/Pages/falcon9/stats/Stat/Stat.js
  src/Pages/falcon9/stats/Stat/Stat.scss
  src/Pages/falcon9/stats/Stats.js
  src/Pages/falcon9/stats/Stats.scss
  src/Styles/common.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#5 [이호현] Refactor: Footer.js, Footer.scss
  src/Components/footer/Footer.js
  src/Components/footer/Footer.scss
Labels: Status: 리뷰 요청

#9 [황연욱] Add: Video Component에 Modal 기능 추가, Fix: Conflict 해결완료
  src/Pages/falcon9/Falcon9.js
  src/Pages/falcon9/Falcon9.scss
  src/Pages/falcon9/Gallery/Slider/ImgCard/ImgCard.scss
  src/Pages/falcon9/Gallery/Slider/Slider.scss
  src/Pages/falcon9/Video/PlayIconSvg.js
  src/Pages/falcon9/Video/PlayIconSvg.scss
  src/Pages/falcon9/Video/Video.js
  src/Pages/falcon9/Video/Video.scss
  src/Pages/falcon9/YoutubeModal/CloseSvg.js
  src/Pages/falcon9/YoutubeModal/CloseSvg.scss
  src/Pages/falcon9/YoutubeModal/DelayUnmounting.js
  src/Pages/falcon9/YoutubeModal/YoutubeModal.js
  src/Pages/falcon9/YoutubeModal/YoutubeModal.scss
  src/Pages/shop/Shop.scss
  src/Routes.js
  src/Styles/common.scss
  src/index.js
Labels: Status: Accepted, Status: 수정 요청

#11 [이호현] Refactor: Main page 수정
  public/data/mainList.json
  src/Components/linkBox/LinkBox.scss
  src/Pages/main/Main.js
  src/Pages/main/Main.scss
  src/Pages/main/component/DownArrow.js
  src/Pages/main/component/DownArrow.scss
  src/Pages/main/component/MainBG.js
  src/Pages/main/component/MainBG.scss
  src/config.js
Labels: Status: 리뷰 요청

#14 [이호현] Add: 장바구니 페이지 추가
  src/Pages/cart/Cart.js
  src/Pages/cart/Cart.scss
  src/Pages/cart/component/CartList.js
  src/Pages/cart/component/CartList.scss
  src/Pages/cart/data.json
Labels: Status: 리뷰 요청

#13 [이호현] Modify: 회원가입 conflict 수정
  src/Pages/register/Register.js
  src/config.js
Labels: Status: 리뷰 요청

#12 [이호현] Modify: 로그인 페이지 conflict 수정
  src/Components/button/Button.js
  src/Components/button/Button.scss
  src/Components/input/Input.js
  src/Pages/account/Account.js
  src/Pages/account/Account.scss
  src/Pages/register/Register.js
Labels: Status: 리뷰 요청

#15 [이호현] Modify: nav bar conflict 수정
  src/Components/nav/Nav.js
  src/Components/nav/Nav.scss
Labels: Status: 리뷰 요청

#18 [이호현] Refactor: 장바구니 페이지 수정, footer 수정
  src/Components/footer/Footer.scss
  src/Pages/cart/Cart.js
  src/Pages/cart/Cart.scss
  src/Pages/cart/component/CartList.js
  src/Pages/cart/component/CartList.scss
  src/Pages/cart/data.json
  src/Routes.js
Labels: Status: 리뷰 요청

#19 [황연욱] Add: scroll Event 추가 Refactor: 코드리뷰사항 반영 리팩토링 실시 Fix:Confilict 해결
  src/Components/nav/Nav.scss
  src/Pages/falcon9/Engines/Engines.js
  src/Pages/falcon9/Falcon9.js
  src/Pages/falcon9/Gallery/Gallery.js
  src/Pages/falcon9/Gallery/Slider/ImgCard/ImgCard.js
  src/Pages/falcon9/Gallery/Slider/Slider.js
  src/Pages/falcon9/ParallaxSlide/ParallaxSlide.js
  src/Pages/falcon9/falcon9Components/SlideWrapper/Card/Card.js
  src/Pages/falcon9/falcon9Components/SlideWrapper/Card/CardContents/CardContents.js
  src/Pages/falcon9/falcon9Components/SlideWrapper/SlideWrapper.js
  src/Pages/falcon9/feature/Feature.js
  src/Pages/falcon9/isInViewHOC.js
  src/Pages/falcon9/stats/Stat/Stat.js
  src/Pages/falcon9/stats/Stats.js
Labels: Status: 리뷰 요청

#16 [송다슬] Modify: Route 추가, Navbar 위치 수정, 유저인증처리 수정, Fix: Confilict 해결
  src/Config.js
  src/Pages/detail/Components/productInfo/ProductInfo.js
  src/Pages/detail/Components/productInfo/ProductInfo.scss
  src/Pages/detail/Components/productSlide/ProductSlide.js
  src/Pages/detail/Detail.js
  src/Pages/detail/colorModal/ColorSelectModal.js
  src/Pages/detail/colorModal/ColorSelectModal.scss
  src/Pages/shop/Components/product/Product.js
  src/Pages/shop/Components/productList/ProductList.js
  src/Pages/shop/Shop.js
  src/Pages/shop/Shop.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
